version: "2"

services:
  #debugger:
  #  image: sjourdan/toolbox
  #  container_name: debugger
  #  networks:
  #    - squirrel
  #  dns: 8.8.8.8
  #  command: nc -l 50070

  frontier:
    image: squirrel
    container_name: frontier
    environment:
      - HOBBIT_RABBIT_HOST=rabbit
      - SEED_FILE=/var/squirrel/data/seeds.txt
      - RDB_HOST_NAME=rethinkdb
      - RDB_PORT=28015
    networks:
      - squirrel
    volumes:
      - ./data/frontier:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.FrontierComponent

  rethinkdb:
    image: rethinkdb:2.3.5
    networks:
      - squirrel
    volumes:
      - ./data/rethinkdb:/data

  # message bus
  rabbit:
    image: rabbitmq:management
    container_name: rabbit
    hostname: rabbit
    networks:
      - squirrel

  worker1:
    image: squirrel
    container_name: worker1
    environment:
      - HOBBIT_RABBIT_HOST=rabbit
      - OUTPUT_FOLDER=/var/squirrel/data
    networks:
      - squirrel
    volumes:
        - ./data/worker1:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.WorkerComponent

  worker2:
    image: squirrel
    container_name: worker2
    environment:
      - HOBBIT_RABBIT_HOST=rabbit
      - OUTPUT_FOLDER=/var/squirrel/data
    networks:
      - squirrel
    volumes:
        - ./data/worker2:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.WorkerComponent

  worker3:
    image: squirrel
    container_name: worker3
    environment:
      - HOBBIT_RABBIT_HOST=rabbit
      - OUTPUT_FOLDER=/var/squirrel/data
    networks:
      - squirrel
    volumes:
        - ./data/worker3:/var/squirrel/data
    command: java -cp squirrel.jar org.hobbit.core.run.ComponentStarter org.aksw.simba.squirrel.components.WorkerComponent

networks:
  squirrel:
    external:
      name: squirrel
